/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IssueTriggerListRequestOrderBy = "created_at" | "type";

export const IssueTriggerListRequestOrderBy = {
    CreatedAt: "created_at",
    Type: "type",
} as const;
