/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../..";

/**
 * Destination input object
 */
export interface ConnectionUpsertRequestDestination {
    /** Name for the destination */
    name: string;
    /** Description for the destination */
    description?: string;
    /** Endpoint of the destination */
    url?: string;
    /** Path for the CLI destination */
    cliPath?: string;
    /** Period to rate limit attempts */
    rateLimitPeriod?: Intercom.ConnectionUpsertRequestDestinationRateLimitPeriod;
    /** Limit event attempts to receive per period */
    rateLimit?: number;
    httpMethod?: Intercom.DestinationHttpMethod;
    authMethod?: Intercom.DestinationAuthMethodConfig;
    pathForwardingDisabled?: boolean;
}
