/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const IgnoredEventBulkRetryCreateRequestQueryWebhookId: core.serialization.Schema<
    serializers.IgnoredEventBulkRetryCreateRequestQueryWebhookId.Raw,
    Intercom.IgnoredEventBulkRetryCreateRequestQueryWebhookId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace IgnoredEventBulkRetryCreateRequestQueryWebhookId {
    type Raw = string | string[];
}
