/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const SourceListRequestDir: core.serialization.Schema<
    serializers.SourceListRequestDir.Raw,
    Hookdeck.SourceListRequestDir
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace SourceListRequestDir {
    type Raw = "asc" | "desc";
}
