/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const EventBulkRetryCreateRequestQueryHeadersOne: core.serialization.ObjectSchema<
    serializers.EventBulkRetryCreateRequestQueryHeadersOne.Raw,
    Intercom.EventBulkRetryCreateRequestQueryHeadersOne
> = core.serialization.object({});

export declare namespace EventBulkRetryCreateRequestQueryHeadersOne {
    interface Raw {}
}
