/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";

export const EventBulkRetryCreateRequestQuerySourceId: core.serialization.Schema<
    serializers.EventBulkRetryCreateRequestQuerySourceId.Raw,
    Hookdeck.EventBulkRetryCreateRequestQuerySourceId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace EventBulkRetryCreateRequestQuerySourceId {
    type Raw = string | string[];
}
