/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";

export const EventBulkRetryCreateRequestQueryHeadersOne: core.serialization.ObjectSchema<
    serializers.EventBulkRetryCreateRequestQueryHeadersOne.Raw,
    Hookdeck.EventBulkRetryCreateRequestQueryHeadersOne
> = core.serialization.object({});

export declare namespace EventBulkRetryCreateRequestQueryHeadersOne {
    interface Raw {}
}
