/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";
import { Operators } from "../../../types/Operators";

export const EventBulkRetryCreateRequestQueryCreatedAt: core.serialization.Schema<
    serializers.EventBulkRetryCreateRequestQueryCreatedAt.Raw,
    Hookdeck.EventBulkRetryCreateRequestQueryCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), Operators]);

export declare namespace EventBulkRetryCreateRequestQueryCreatedAt {
    type Raw = string | Operators.Raw;
}
