/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";
import { EventBulkRetryCreateRequestQueryBodyOne } from "./EventBulkRetryCreateRequestQueryBodyOne";

export const EventBulkRetryCreateRequestQueryBody: core.serialization.Schema<
    serializers.EventBulkRetryCreateRequestQueryBody.Raw,
    Hookdeck.EventBulkRetryCreateRequestQueryBody
> = core.serialization.undiscriminatedUnion([core.serialization.string(), EventBulkRetryCreateRequestQueryBodyOne]);

export declare namespace EventBulkRetryCreateRequestQueryBody {
    type Raw = string | EventBulkRetryCreateRequestQueryBodyOne.Raw;
}
