/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";
import { EventBulkRetryCreateRequestQueryAttemptsAll } from "./EventBulkRetryCreateRequestQueryAttemptsAll";

export const EventBulkRetryCreateRequestQueryAttempts: core.serialization.Schema<
    serializers.EventBulkRetryCreateRequestQueryAttempts.Raw,
    Intercom.EventBulkRetryCreateRequestQueryAttempts
> = core.serialization.undiscriminatedUnion([core.serialization.number(), EventBulkRetryCreateRequestQueryAttemptsAll]);

export declare namespace EventBulkRetryCreateRequestQueryAttempts {
    type Raw = number | EventBulkRetryCreateRequestQueryAttemptsAll.Raw;
}
