/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const EventBulkRetryCreateRequestQueryCliUserId: core.serialization.Schema<
    serializers.EventBulkRetryCreateRequestQueryCliUserId.Raw,
    Hookdeck.EventBulkRetryCreateRequestQueryCliUserId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace EventBulkRetryCreateRequestQueryCliUserId {
    type Raw = string | string[];
}
