/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Hookdeck from "../index";

export class GoneError extends errors.HookdeckError {
    constructor(body: Hookdeck.ApiErrorResponse) {
        super({
            message: "GoneError",
            statusCode: 410,
            body: body,
        });
        Object.setPrototypeOf(this, GoneError.prototype);
    }
}
