/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../..";

/**
 * @example
 *     {}
 */
export interface IssueTriggerListRequest {
    name?: string;
    type?: Intercom.IssueType;
    disabledAt?: Date;
    orderBy?: Intercom.IssueTriggerListRequestOrderBy;
    dir?: Intercom.IssueTriggerListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
