/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../..";

/**
 * @example
 *     {}
 */
export interface RequestBulkRetryListRequest {
    cancelledAt?: Date;
    completedAt?: Date;
    createdAt?: Date;
    id?: string;
    inProgress?: boolean;
    queryPartialMatch?: boolean;
    orderBy?: Intercom.RequestBulkRetryListRequestOrderBy;
    dir?: Intercom.RequestBulkRetryListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
