/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AttemptListRequestDir = "asc" | "desc";

export const AttemptListRequestDir = {
    Asc: "asc",
    Desc: "desc",
} as const;
