/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const ConnectionListRequestDir: core.serialization.Schema<
    serializers.ConnectionListRequestDir.Raw,
    Hookdeck.ConnectionListRequestDir
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace ConnectionListRequestDir {
    type Raw = "asc" | "desc";
}
