/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const ConnectionCreateRequestDestinationRateLimitPeriod: core.serialization.Schema<
    serializers.ConnectionCreateRequestDestinationRateLimitPeriod.Raw,
    Intercom.ConnectionCreateRequestDestinationRateLimitPeriod
> = core.serialization.enum_(["second", "minute", "hour"]);

export declare namespace ConnectionCreateRequestDestinationRateLimitPeriod {
    type Raw = "second" | "minute" | "hour";
}
