/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Connection ID of the ignored event
 */
export type IgnoredEventBulkRetryCreateRequestQueryWebhookId = string | string[];
