/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../../index";

/**
 * @example
 *     {}
 */
export interface AttemptListRequest {
    eventId?: string | string[];
    orderBy?: Hookdeck.AttemptListRequestOrderBy;
    dir?: Hookdeck.AttemptListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
