/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const RequestListIgnoredEventRequestOrderBy: core.serialization.Schema<
    serializers.RequestListIgnoredEventRequestOrderBy.Raw,
    Hookdeck.RequestListIgnoredEventRequestOrderBy
> = core.serialization.enum_(["created_at"]);

export declare namespace RequestListIgnoredEventRequestOrderBy {
    type Raw = "created_at";
}
