/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Hookdeck from "../../../../../api";
import * as core from "../../../../../core";
import { BookmarkTriggerRequestTarget } from "../../types/BookmarkTriggerRequestTarget";

export const BookmarkTriggerRequest: core.serialization.Schema<
    serializers.BookmarkTriggerRequest.Raw,
    Hookdeck.BookmarkTriggerRequest
> = core.serialization.object({
    target: BookmarkTriggerRequestTarget.optional(),
});

export declare namespace BookmarkTriggerRequest {
    interface Raw {
        target?: BookmarkTriggerRequestTarget.Raw | null;
    }
}
