/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IssueCountRequestStatus = "OPENED" | "IGNORED" | "ACKNOWLEDGED" | "RESOLVED";

export const IssueCountRequestStatus = {
    Opened: "OPENED",
    Ignored: "IGNORED",
    Acknowledged: "ACKNOWLEDGED",
    Resolved: "RESOLVED",
} as const;
