/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * New status
 */
export type IssueUpdateRequestStatus = "OPENED" | "IGNORED" | "ACKNOWLEDGED" | "RESOLVED";

export const IssueUpdateRequestStatus = {
    Opened: "OPENED",
    Ignored: "IGNORED",
    Acknowledged: "ACKNOWLEDGED",
    Resolved: "RESOLVED",
} as const;
