/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";
import { RequestBulkRetryCreateRequestQueryParsedQueryOne } from "./RequestBulkRetryCreateRequestQueryParsedQueryOne";

export const RequestBulkRetryCreateRequestQueryParsedQuery: core.serialization.Schema<
    serializers.RequestBulkRetryCreateRequestQueryParsedQuery.Raw,
    Intercom.RequestBulkRetryCreateRequestQueryParsedQuery
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    RequestBulkRetryCreateRequestQueryParsedQueryOne,
]);

export declare namespace RequestBulkRetryCreateRequestQueryParsedQuery {
    type Raw = string | RequestBulkRetryCreateRequestQueryParsedQueryOne.Raw;
}
