/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const RequestBulkRetryListRequestDir: core.serialization.Schema<
    serializers.RequestBulkRetryListRequestDir.Raw,
    Hookdeck.RequestBulkRetryListRequestDir
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace RequestBulkRetryListRequestDir {
    type Raw = "asc" | "desc";
}
