/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AttemptState = "DELIVERING" | "QUEUED" | "PENDING" | "COMPLETED" | "HOLD";

export const AttemptState = {
    Delivering: "DELIVERING",
    Queued: "QUEUED",
    Pending: "PENDING",
    Completed: "COMPLETED",
    Hold: "HOLD",
} as const;
