/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Attempt status
 */
export type AttemptStatus = "QUEUED" | "FAILED" | "SUCCESSFUL" | "HOLD";

export const AttemptStatus = {
    Queued: "QUEUED",
    Failed: "FAILED",
    Successful: "SUCCESSFUL",
    Hold: "HOLD",
} as const;
