/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

/**
 * Basic Auth
 */
export interface AuthBasicAuth {
    config?: Hookdeck.DestinationAuthMethodBasicAuthConfig;
}
