/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

/**
 * OAuth2 Client Credentials
 */
export interface AuthOAuth2ClientCredentials {
    config?: Hookdeck.DestinationAuthMethodOAuth2ClientCredentialsConfig;
}
