/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

/**
 * API Key
 */
export interface AuthApiKey {
    config?: Hookdeck.DestinationAuthMethodApiKeyConfig;
}
