/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

export interface BookmarkPaginatedResult {
    pagination?: Hookdeck.SeekPagination;
    count?: number;
    models?: Hookdeck.Bookmark[];
}
