/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

export interface ConsoleLine {
    type: Hookdeck.ConsoleLineType;
    message: string;
}
