/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

/**
 * Delivery issue data
 */
export interface DeliveryIssueData {
    triggerEvent?: Hookdeck.Event;
    triggerAttempt?: Hookdeck.EventAttempt;
}
