/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Basic (default), Bearer Authentication or x-www-form-urlencoded
 */
export type DestinationAuthMethodOAuth2ClientCredentialsConfigAuthenticationType =
    | "basic"
    | "bearer"
    | "x-www-form-urlencoded";

export const DestinationAuthMethodOAuth2ClientCredentialsConfigAuthenticationType = {
    Basic: "basic",
    Bearer: "bearer",
    XWwwFormUrlencoded: "x-www-form-urlencoded",
} as const;
