/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface Event {
    /** ID of the event */
    id: string;
    /** ID of the workspace */
    teamId: string;
    /** ID of the associated connection */
    webhookId: string;
    /** ID of the associated source */
    sourceId: string;
    /** ID of the associated destination */
    destinationId: string;
    /** ID of the event data */
    eventDataId: string;
    /** ID of the request that created the event */
    requestId: string;
    /** Number of delivery attempts made */
    attempts: number;
    /** Date of the most recently attempted retry */
    lastAttemptAt?: Date;
    /** Date of the next scheduled retry */
    nextAttemptAt?: Date;
    /** Event status */
    responseStatus?: number;
    errorCode?: Intercom.AttemptErrorCodes;
    status: Intercom.EventStatus;
    /** Date of the latest successful attempt */
    successfulAt?: Date;
    /** ID of the CLI the event is sent to */
    cliId?: string;
    /** Date the event was last updated */
    updatedAt: Date;
    /** Date the event was created */
    createdAt: Date;
    data?: Intercom.ShortEventData;
}
