/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export type EventAttemptBody =
    /**
     * Response body from the destination */
    | Intercom.EventAttemptBodyZero
    | undefined
    /**
     * Response body from the destination */
    | string
    | undefined;
