/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

export interface EventAttemptPaginatedResult {
    pagination?: Hookdeck.SeekPagination;
    count?: number;
    models?: (Hookdeck.EventAttempt | undefined)[];
}
