/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

export interface HmacIntegrationConfigs {
    webhookSecretKey: string;
    algorithm: Hookdeck.HmacAlgorithms;
    headerKey: string;
    encoding: Hookdeck.HmacIntegrationConfigsEncoding;
}
