/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IgnoredEventCause = "DISABLED" | "FILTERED" | "TRANSFORMATION_FAILED" | "CLI_DISCONNECTED";

export const IgnoredEventCause = {
    Disabled: "DISABLED",
    Filtered: "FILTERED",
    TransformationFailed: "TRANSFORMATION_FAILED",
    CliDisconnected: "CLI_DISCONNECTED",
} as const;
