/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

export interface IgnoredEvent {
    id: string;
    /** ID of the project */
    teamId: string;
    webhookId: string;
    cause: Hookdeck.IgnoredEventCause;
    requestId: string;
    meta?: Hookdeck.IgnoredEventMeta;
    createdAt: Date;
}
