/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

/**
 * Decrypted Key/Value object of the associated configuration for that provider
 */
export type IntegrationConfigs =
    | Intercom.HmacIntegrationConfigs
    | Intercom.ApiKeyIntegrationConfigs
    | Intercom.HandledApiKeyIntegrationConfigs
    | Intercom.HandledHmacConfigs
    | Intercom.BasicAuthIntegrationConfigs
    | Intercom.ShopifyIntegrationConfigs
    | Intercom.IntegrationConfigsSix;
