/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

/**
 * Decrypted Key/Value object of the associated configuration for that provider
 */
export type IntegrationConfigs =
    | Hookdeck.HmacIntegrationConfigs
    | Hookdeck.ApiKeyIntegrationConfigs
    | Hookdeck.HandledApiKeyIntegrationConfigs
    | Hookdeck.HandledHmacConfigs
    | Hookdeck.BasicAuthIntegrationConfigs
    | Hookdeck.ShopifyIntegrationConfigs
    | Hookdeck.IntegrationConfigsSix;
