/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

export interface Integration {
    /** ID of the integration */
    id: string;
    /** ID of the workspace */
    teamId: string;
    /** Label of the integration */
    label: string;
    provider: Hookdeck.IntegrationProvider;
    /** List of features to enable (see features list below) */
    features: Hookdeck.IntegrationFeature[];
    /** Decrypted Key/Value object of the associated configuration for that provider */
    configs: Hookdeck.IntegrationConfigs;
    /** List of source IDs the integration is attached to */
    sources: string[];
    /** Date the integration was last updated */
    updatedAt: Date;
    /** Date the integration was created */
    createdAt: Date;
}
