/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A pattern to match on the connection name or array of connection IDs. Use `*` as wildcard.
 */
export type IssueTriggerDeliveryConfigsConnections = string | string[];
