/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

/**
 * Notification channels object for the specific channel type
 */
export interface IssueTriggerChannels {
    slack?: Intercom.IssueTriggerSlackChannel;
    opsgenie?: Intercom.IssueTriggerIntegrationChannel;
    email?: Intercom.IssueTriggerEmailChannel;
}
