/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Algorithm to use when calculating delay between retries
 */
export type RetryStrategy = "linear" | "exponential";

export const RetryStrategy = {
    Linear: "linear",
    Exponential: "exponential",
} as const;
