/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

/**
 * JSON representation of query params
 */
export type ShortEventDataParsedQuery = string | undefined | Hookdeck.ShortEventDataParsedQueryOne;
