/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

/**
 * JSON or string representation of the body
 */
export type ShortEventDataBody = string | Hookdeck.ShortEventDataBodyOne | unknown[];
