/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

/**
 * Associated [Source](#source-object) object
 */
export interface Source {
    /** ID of the source */
    id: string;
    /** Name for the source */
    name: string;
    /** Description of the source */
    description?: string;
    /** ID of the workspace */
    teamId: string;
    /** A unique URL that must be supplied to your webhook's provider */
    url: string;
    verification?: Intercom.SourceVerification;
    allowedHttpMethods?: Intercom.SourceAllowedHttpMethod | undefined;
    customResponse?: Intercom.SourceCustomResponse;
    /** Date the source was disabled */
    disabledAt?: Date;
    /** Date the source was last updated */
    updatedAt: Date;
    /** Date the source was created */
    createdAt: Date;
}
