/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface ToggleWebhookNotifications {
    enabled: boolean;
    topics?: Intercom.TopicsValue[];
    sourceId: string;
}
