/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

/**
 * Keys used as the aggregation keys a 'transformation' type issue
 */
export interface TransformationIssueAggregationKeys {
    transformationId: string[];
    logLevel: Hookdeck.TransformationExecutionLogLevel;
}
