/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

/**
 * Transformation issue data
 */
export interface TransformationIssueData {
    transformationExecution: Hookdeck.TransformationExecution;
    triggerAttempt?: Hookdeck.EventAttempt;
}
