/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationShopifyConfigsRateLimitPeriod = "minute" | "second";

export const VerificationShopifyConfigsRateLimitPeriod = {
    Minute: "minute",
    Second: "second",
} as const;
