/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationTokenIoType = "tokenio" | "TOKENIO";

export const VerificationTokenIoType = {
    Tokenio: "tokenio",
    Tokenio: "TOKENIO",
} as const;
