/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationNmiPaymentGatewayType = "nmi" | "NMI";

export const VerificationNmiPaymentGatewayType = {
    Nmi: "nmi",
    Nmi: "NMI",
} as const;
