/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationFavroType = "favro" | "FAVRO";

export const VerificationFavroType = {
    Favro: "favro",
    Favro: "FAVRO",
} as const;
