/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

export interface VerificationSolidGate {
    type: Hookdeck.VerificationSolidGateType;
    configs?: Hookdeck.VerificationSolidGateConfigs;
}
