/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationRechargeType = "recharge" | "RECHARGE";

export const VerificationRechargeType = {
    Recharge: "recharge",
    Recharge: "RECHARGE",
} as const;
