/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationShopifyType = "shopify";

export const VerificationShopifyType = {
    Shopify: "shopify",
} as const;
