/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationTrelloType = "trello" | "TRELLO";

export const VerificationTrelloType = {
    Trello: "trello",
    Trello: "TRELLO",
} as const;
