/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationHmacConfigsEncoding = "base64" | "base64url" | "hex";

export const VerificationHmacConfigsEncoding = {
    Base64: "base64",
    Base64Url: "base64url",
    Hex: "hex",
} as const;
