/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface VerificationPersona {
    type: Intercom.VerificationPersonaType;
    configs?: Intercom.VerificationPersonaConfigs;
}
