/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

export interface VerificationCommercelayer {
    type: Hookdeck.VerificationCommercelayerType;
    configs?: Hookdeck.VerificationCommercelayerConfigs;
}
