/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationSyncteraType = "synctera" | "SYNCTERA";

export const VerificationSyncteraType = {
    Synctera: "synctera",
    Synctera: "SYNCTERA",
} as const;
