/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The verification configs for Shopline. Only included if the ?include=verification.configs query param is present
 */
export interface VerificationShoplineConfigs {
    webhookSecretKey: string;
}
