/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationStripeType = "stripe" | "STRIPE";

export const VerificationStripeType = {
    Stripe: "stripe",
    Stripe: "STRIPE",
} as const;
