/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationPipedriveType = "pipedrive";

export const VerificationPipedriveType = {
    Pipedrive: "pipedrive",
} as const;
