/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationWooCommerceType = "woocommerce";

export const VerificationWooCommerceType = {
    Woocommerce: "woocommerce",
} as const;
