/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface VerificationSynctera {
    type: Intercom.VerificationSyncteraType;
    configs?: Intercom.VerificationSyncteraConfigs;
}
