/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationLinearType = "linear" | "LINEAR";

export const VerificationLinearType = {
    Linear: "linear",
    Linear: "LINEAR",
} as const;
