/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationEbayType = "ebay" | "EBAY";

export const VerificationEbayType = {
    Ebay: "ebay",
    Ebay: "EBAY",
} as const;
