/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationSquareType = "square" | "SQUARE";

export const VerificationSquareType = {
    Square: "square",
    Square: "SQUARE",
} as const;
