/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

export interface VerificationRecharge {
    type: Hookdeck.VerificationRechargeType;
    configs?: Hookdeck.VerificationRechargeConfigs;
}
