/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

export interface VerificationShopify {
    configs?: Hookdeck.VerificationShopifyConfigs;
}
