/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface VerificationSendGrid {
    type: Intercom.VerificationSendGridType;
    configs?: Intercom.VerificationSendGridConfigs;
}
