/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../index";

export interface VerificationTypeform {
    type: Hookdeck.VerificationTypeformType;
    configs?: Hookdeck.VerificationTypeformConfigs;
}
