/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationXeroType = "xero" | "XERO";

export const VerificationXeroType = {
    Xero: "xero",
    Xero: "XERO",
} as const;
