/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface VerificationWooCommerce {
    type: Intercom.VerificationWooCommerceType;
    configs?: Intercom.VerificationWooCommerceConfigs;
}
