/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationSendGridType = "sendgrid" | "SENDGRID";

export const VerificationSendGridType = {
    Sendgrid: "sendgrid",
    Sendgrid: "SENDGRID",
} as const;
