/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The verification configs for Mailchimp. Only included if the ?include=verification.configs query param is present
 */
export interface VerificationMailchimpConfigs {
    webhookSecretKey: string;
}
