/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationApiKeyType = "api_key" | "API_KEY";

export const VerificationApiKeyType = {
    ApiKey: "api_key",
    ApiKey: "API_KEY",
} as const;
