/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationSendGridType = "sendgrid";

export const VerificationSendGridType = {
    Sendgrid: "sendgrid",
} as const;
