/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The verification configs for Paypal. Only included if the ?include=verification.configs query param is present
 */
export interface VerificationPaypalConfigs {
    webhookId: string;
}
