/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "..";

export interface VerificationAkeneo {
    type: Hookdeck.VerificationAkeneoType;
    configs?: Hookdeck.VerificationAkeneoConfigs;
}
