/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerificationHubspotType = "hubspot";

export const VerificationHubspotType = {
    Hubspot: "hubspot",
} as const;
