/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "..";

export interface VerificationCommercelayer {
    type: Intercom.VerificationCommercelayerType;
    configs?: Intercom.VerificationCommercelayerConfigs;
}
