/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Verification3DEyeType = "three_d_eye";

export const Verification3DEyeType = {
    ThreeDEye: "three_d_eye",
} as const;
