/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../..";

/**
 * @example
 *     {}
 */
export interface TransformationListRequest {
    id?: string;
    name?: string;
    orderBy?: Hookdeck.TransformationListRequestOrderBy;
    dir?: Hookdeck.TransformationListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
