/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 */
export interface TransformationUpdateRequest {
    /** A unique, human-friendly name for the transformation */
    name?: string;
    /** JavaScript code to be executed */
    code?: string;
    /** Key-value environment variables to be passed to the transformation */
    env?: Record<string, string>;
}
