/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";
import { EventAttempt } from "../../../types/EventAttempt";

export const Response: core.serialization.Schema<
    serializers.attempt.retrieve.Response.Raw,
    Intercom.EventAttempt | undefined
> = EventAttempt.optional();

export declare namespace Response {
    type Raw = EventAttempt.Raw | null | undefined;
}
