/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const DestinationUpsertRequestRateLimitPeriod: core.serialization.Schema<
    serializers.DestinationUpsertRequestRateLimitPeriod.Raw,
    Intercom.DestinationUpsertRequestRateLimitPeriod
> = core.serialization.enum_(["second", "minute", "hour"]);

export declare namespace DestinationUpsertRequestRateLimitPeriod {
    type Raw = "second" | "minute" | "hour";
}
