/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const DestinationUpdateRequestRateLimitPeriod: core.serialization.Schema<
    serializers.DestinationUpdateRequestRateLimitPeriod.Raw,
    Intercom.DestinationUpdateRequestRateLimitPeriod
> = core.serialization.enum_(["second", "minute", "hour"]);

export declare namespace DestinationUpdateRequestRateLimitPeriod {
    type Raw = "second" | "minute" | "hour";
}
