/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Filter by status
 */
export type RequestListRequestStatus = "accepted" | "rejected";

export const RequestListRequestStatus = {
    Accepted: "accepted",
    Rejected: "rejected",
} as const;
