/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sort key
 */
export type RequestListEventRequestOrderBy = "last_attempt_at" | "created_at";

export const RequestListEventRequestOrderBy = {
    LastAttemptAt: "last_attempt_at",
    CreatedAt: "created_at",
} as const;
