/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../..";

/**
 * @example
 *     {
 *         id: "iss_YXKv5OdJXCiVwkPhGy",
 *         issueTriggerId: "it_BXKv5OdJXCiVwkPhGy",
 *         mergedWith: "iss_AXKv3OdJXCiKlkPhDz"
 *     }
 */
export interface IssueCountRequest {
    id?: string;
    issueTriggerId?: string;
    type?: Intercom.IssueCountRequestType;
    status?: Intercom.IssueCountRequestStatus;
    mergedWith?: string;
    createdAt?: Date;
    firstSeenAt?: Date;
    lastSeenAt?: Date;
    dismissedAt?: Date;
    orderBy?: Intercom.IssueCountRequestOrderBy;
    dir?: Intercom.IssueCountRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
