/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const AttemptTrigger: core.serialization.Schema<serializers.AttemptTrigger.Raw, Hookdeck.AttemptTrigger> =
    core.serialization.enum_(["INITIAL", "MANUAL", "BULK_RETRY", "UNPAUSE", "AUTOMATIC"]);

export declare namespace AttemptTrigger {
    type Raw = "INITIAL" | "MANUAL" | "BULK_RETRY" | "UNPAUSE" | "AUTOMATIC";
}
