/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const AttemptStatus: core.serialization.Schema<serializers.AttemptStatus.Raw, Hookdeck.AttemptStatus> =
    core.serialization.enum_(["QUEUED", "FAILED", "SUCCESSFUL", "HOLD"]);

export declare namespace AttemptStatus {
    type Raw = "QUEUED" | "FAILED" | "SUCCESSFUL" | "HOLD";
}
