/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { DestinationAuthMethodApiKeyConfig } from "./DestinationAuthMethodApiKeyConfig";

export const AuthApiKey: core.serialization.ObjectSchema<serializers.AuthApiKey.Raw, Hookdeck.AuthApiKey> =
    core.serialization.object({
        config: DestinationAuthMethodApiKeyConfig.optional(),
    });

export declare namespace AuthApiKey {
    interface Raw {
        config?: DestinationAuthMethodApiKeyConfig.Raw | null;
    }
}
