/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { SeekPagination } from "./SeekPagination";
import { BatchOperation } from "./BatchOperation";

export const BatchOperationPaginatedResult: core.serialization.ObjectSchema<
    serializers.BatchOperationPaginatedResult.Raw,
    Intercom.BatchOperationPaginatedResult
> = core.serialization.object({
    pagination: SeekPagination.optional(),
    count: core.serialization.number().optional(),
    models: core.serialization.list(BatchOperation).optional(),
});

export declare namespace BatchOperationPaginatedResult {
    interface Raw {
        pagination?: SeekPagination.Raw | null;
        count?: number | null;
        models?: BatchOperation.Raw[] | null;
    }
}
