/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { ConsoleLineType } from "./ConsoleLineType";

export const ConsoleLine: core.serialization.ObjectSchema<serializers.ConsoleLine.Raw, Intercom.ConsoleLine> =
    core.serialization.object({
        type: ConsoleLineType,
        message: core.serialization.string(),
    });

export declare namespace ConsoleLine {
    interface Raw {
        type: ConsoleLineType.Raw;
        message: string;
    }
}
