/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const ConsoleLineType: core.serialization.Schema<serializers.ConsoleLineType.Raw, Hookdeck.ConsoleLineType> =
    core.serialization.enum_(["error", "log", "warn", "info", "debug"]);

export declare namespace ConsoleLineType {
    type Raw = "error" | "log" | "warn" | "info" | "debug";
}
