/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const DeletedBookmarkResponse: core.serialization.ObjectSchema<
    serializers.DeletedBookmarkResponse.Raw,
    Intercom.DeletedBookmarkResponse
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace DeletedBookmarkResponse {
    interface Raw {
        id: string;
    }
}
