/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { Event } from "./Event";
import { EventAttempt } from "./EventAttempt";

export const DeliveryIssueData: core.serialization.ObjectSchema<
    serializers.DeliveryIssueData.Raw,
    Intercom.DeliveryIssueData
> = core.serialization.object({
    triggerEvent: core.serialization.property("trigger_event", Event.optional()),
    triggerAttempt: core.serialization.property("trigger_attempt", EventAttempt.optional()),
});

export declare namespace DeliveryIssueData {
    interface Raw {
        trigger_event?: Event.Raw | null;
        trigger_attempt?: EventAttempt.Raw | null;
    }
}
