/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const DestinationAuthMethodOAuth2ClientCredentialsConfig: core.serialization.ObjectSchema<
    serializers.DestinationAuthMethodOAuth2ClientCredentialsConfig.Raw,
    Intercom.DestinationAuthMethodOAuth2ClientCredentialsConfig
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string()),
    scope: core.serialization.string().optional(),
    authServer: core.serialization.property("auth_server", core.serialization.string()),
});

export declare namespace DestinationAuthMethodOAuth2ClientCredentialsConfig {
    interface Raw {
        client_id: string;
        client_secret: string;
        scope?: string | null;
        auth_server: string;
    }
}
