/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const DestinationAuthMethodSignatureConfig: core.serialization.ObjectSchema<
    serializers.DestinationAuthMethodSignatureConfig.Raw,
    Intercom.DestinationAuthMethodSignatureConfig
> = core.serialization.object({});

export declare namespace DestinationAuthMethodSignatureConfig {
    interface Raw {}
}
