/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { SeekPagination } from "./SeekPagination";
import { Destination } from "./Destination";

export const DestinationPaginatedResult: core.serialization.ObjectSchema<
    serializers.DestinationPaginatedResult.Raw,
    Hookdeck.DestinationPaginatedResult
> = core.serialization.object({
    pagination: SeekPagination.optional(),
    count: core.serialization.number().optional(),
    models: core.serialization.list(Destination).optional(),
});

export declare namespace DestinationPaginatedResult {
    interface Raw {
        pagination?: SeekPagination.Raw | null;
        count?: number | null;
        models?: Destination.Raw[] | null;
    }
}
