/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { DestinationAuthMethodApiKeyConfigTo } from "./DestinationAuthMethodApiKeyConfigTo";

export const DestinationAuthMethodApiKeyConfig: core.serialization.ObjectSchema<
    serializers.DestinationAuthMethodApiKeyConfig.Raw,
    Hookdeck.DestinationAuthMethodApiKeyConfig
> = core.serialization.object({
    key: core.serialization.string(),
    apiKey: core.serialization.property("api_key", core.serialization.string()),
    to: DestinationAuthMethodApiKeyConfigTo.optional(),
});

export declare namespace DestinationAuthMethodApiKeyConfig {
    interface Raw {
        key: string;
        api_key: string;
        to?: DestinationAuthMethodApiKeyConfigTo.Raw | null;
    }
}
