/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const DestinationAuthMethodApiKeyConfigTo: core.serialization.Schema<
    serializers.DestinationAuthMethodApiKeyConfigTo.Raw,
    Intercom.DestinationAuthMethodApiKeyConfigTo
> = core.serialization.enum_(["header", "query"]);

export declare namespace DestinationAuthMethodApiKeyConfigTo {
    type Raw = "header" | "query";
}
