/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const DestinationAuthMethodSignatureConfig: core.serialization.ObjectSchema<
    serializers.DestinationAuthMethodSignatureConfig.Raw,
    Hookdeck.DestinationAuthMethodSignatureConfig
> = core.serialization.object({});

export declare namespace DestinationAuthMethodSignatureConfig {
    interface Raw {}
}
