/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { Event } from "./Event";

export const EventArray: core.serialization.Schema<serializers.EventArray.Raw, Hookdeck.EventArray> =
    core.serialization.list(Event);

export declare namespace EventArray {
    type Raw = Event.Raw[];
}
