/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const EventAttemptBodyZero: core.serialization.ObjectSchema<
    serializers.EventAttemptBodyZero.Raw,
    Hookdeck.EventAttemptBodyZero
> = core.serialization.object({});

export declare namespace EventAttemptBodyZero {
    interface Raw {}
}
