/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const FilteredMetaItem: core.serialization.Schema<serializers.FilteredMetaItem.Raw, Hookdeck.FilteredMetaItem> =
    core.serialization.enum_(["body", "headers", "path", "query"]);

export declare namespace FilteredMetaItem {
    type Raw = "body" | "headers" | "path" | "query";
}
