/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const FilterRuleProperty: core.serialization.Schema<
    serializers.FilterRuleProperty.Raw,
    Intercom.FilterRuleProperty
> = core.serialization.undiscriminatedUnion([
    core.serialization.string().optional(),
    core.serialization.number().optional(),
    core.serialization.boolean().optional(),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
]);

export declare namespace FilterRuleProperty {
    type Raw =
        | (string | null | undefined)
        | (number | null | undefined)
        | (boolean | null | undefined)
        | (Record<string, unknown> | null | undefined);
}
