/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const HmacIntegrationConfigsEncoding: core.serialization.Schema<
    serializers.HmacIntegrationConfigsEncoding.Raw,
    Hookdeck.HmacIntegrationConfigsEncoding
> = core.serialization.enum_(["base64", "hex"]);

export declare namespace HmacIntegrationConfigsEncoding {
    type Raw = "base64" | "hex";
}
