/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { SeekPagination } from "./SeekPagination";
import { IgnoredEvent } from "./IgnoredEvent";

export const IgnoredEventPaginatedResult: core.serialization.ObjectSchema<
    serializers.IgnoredEventPaginatedResult.Raw,
    Hookdeck.IgnoredEventPaginatedResult
> = core.serialization.object({
    pagination: SeekPagination.optional(),
    count: core.serialization.number().optional(),
    models: core.serialization.list(IgnoredEvent).optional(),
});

export declare namespace IgnoredEventPaginatedResult {
    interface Raw {
        pagination?: SeekPagination.Raw | null;
        count?: number | null;
        models?: IgnoredEvent.Raw[] | null;
    }
}
