/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const IntegrationConfigsSix: core.serialization.ObjectSchema<
    serializers.IntegrationConfigsSix.Raw,
    Hookdeck.IntegrationConfigsSix
> = core.serialization.object({});

export declare namespace IntegrationConfigsSix {
    interface Raw {}
}
