/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const IssueStatus: core.serialization.Schema<serializers.IssueStatus.Raw, Intercom.IssueStatus> =
    core.serialization.enum_(["OPENED", "IGNORED", "ACKNOWLEDGED", "RESOLVED"]);

export declare namespace IssueStatus {
    type Raw = "OPENED" | "IGNORED" | "ACKNOWLEDGED" | "RESOLVED";
}
