/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const IssueCount: core.serialization.ObjectSchema<serializers.IssueCount.Raw, Intercom.IssueCount> =
    core.serialization.object({
        count: core.serialization.number(),
    });

export declare namespace IssueCount {
    interface Raw {
        count: number;
    }
}
