/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const IssueTriggerIntegrationChannel: core.serialization.ObjectSchema<
    serializers.IssueTriggerIntegrationChannel.Raw,
    Intercom.IssueTriggerIntegrationChannel
> = core.serialization.object({});

export declare namespace IssueTriggerIntegrationChannel {
    interface Raw {}
}
