/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const IssueTriggerBackpressureConfigsDestinations: core.serialization.Schema<
    serializers.IssueTriggerBackpressureConfigsDestinations.Raw,
    Hookdeck.IssueTriggerBackpressureConfigsDestinations
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace IssueTriggerBackpressureConfigsDestinations {
    type Raw = string | string[];
}
