/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { IssueTriggerSlackChannel } from "./IssueTriggerSlackChannel";
import { IssueTriggerIntegrationChannel } from "./IssueTriggerIntegrationChannel";
import { IssueTriggerEmailChannel } from "./IssueTriggerEmailChannel";

export const IssueTriggerChannels: core.serialization.ObjectSchema<
    serializers.IssueTriggerChannels.Raw,
    Hookdeck.IssueTriggerChannels
> = core.serialization.object({
    slack: IssueTriggerSlackChannel.optional(),
    opsgenie: IssueTriggerIntegrationChannel.optional(),
    email: IssueTriggerEmailChannel.optional(),
});

export declare namespace IssueTriggerChannels {
    interface Raw {
        slack?: IssueTriggerSlackChannel.Raw | null;
        opsgenie?: IssueTriggerIntegrationChannel.Raw | null;
        email?: IssueTriggerEmailChannel.Raw | null;
    }
}
