/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const IssueTriggerBackpressureDelay: core.serialization.Schema<
    serializers.IssueTriggerBackpressureDelay.Raw,
    Hookdeck.IssueTriggerBackpressureDelay
> = core.serialization.number();

export declare namespace IssueTriggerBackpressureDelay {
    type Raw = number;
}
