/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const IssueTriggerStrategy: core.serialization.Schema<
    serializers.IssueTriggerStrategy.Raw,
    Hookdeck.IssueTriggerStrategy
> = core.serialization.enum_(["first_attempt", "final_attempt"]);

export declare namespace IssueTriggerStrategy {
    type Raw = "first_attempt" | "final_attempt";
}
