/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { TransformationExecutionLogLevel } from "./TransformationExecutionLogLevel";
import { IssueTriggerTransformationConfigsTransformations } from "./IssueTriggerTransformationConfigsTransformations";

export const IssueTriggerTransformationConfigs: core.serialization.ObjectSchema<
    serializers.IssueTriggerTransformationConfigs.Raw,
    Intercom.IssueTriggerTransformationConfigs
> = core.serialization.object({
    logLevel: core.serialization.property("log_level", TransformationExecutionLogLevel),
    transformations: IssueTriggerTransformationConfigsTransformations,
});

export declare namespace IssueTriggerTransformationConfigs {
    interface Raw {
        log_level: TransformationExecutionLogLevel.Raw;
        transformations: IssueTriggerTransformationConfigsTransformations.Raw;
    }
}
