/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { ListCustomDomainSchemaItem } from "./ListCustomDomainSchemaItem";

export const ListCustomDomainSchema: core.serialization.Schema<
    serializers.ListCustomDomainSchema.Raw,
    Hookdeck.ListCustomDomainSchema
> = core.serialization.list(ListCustomDomainSchemaItem);

export declare namespace ListCustomDomainSchema {
    type Raw = ListCustomDomainSchemaItem.Raw[];
}
