/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const ListCustomDomainSchemaItemSslSettings: core.serialization.ObjectSchema<
    serializers.ListCustomDomainSchemaItemSslSettings.Raw,
    Intercom.ListCustomDomainSchemaItemSslSettings
> = core.serialization.object({
    minTlsVersion: core.serialization.property("min_tls_version", core.serialization.string().optional()),
});

export declare namespace ListCustomDomainSchemaItemSslSettings {
    interface Raw {
        min_tls_version?: string | null;
    }
}
