/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const RawBody: core.serialization.ObjectSchema<serializers.RawBody.Raw, Hookdeck.RawBody> =
    core.serialization.object({
        body: core.serialization.string(),
    });

export declare namespace RawBody {
    interface Raw {
        body: string;
    }
}
