/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { RetryRule } from "./RetryRule";
import { FilterRule } from "./FilterRule";
import { TransformRule } from "./TransformRule";
import { DelayRule } from "./DelayRule";

export const Rule: core.serialization.Schema<serializers.Rule.Raw, Hookdeck.Rule> =
    core.serialization.undiscriminatedUnion([RetryRule, FilterRule, TransformRule, DelayRule]);

export declare namespace Rule {
    type Raw = RetryRule.Raw | FilterRule.Raw | TransformRule.Raw | DelayRule.Raw;
}
