/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const ShopifyIntegrationConfigsRateLimitPeriod: core.serialization.Schema<
    serializers.ShopifyIntegrationConfigsRateLimitPeriod.Raw,
    Intercom.ShopifyIntegrationConfigsRateLimitPeriod
> = core.serialization.enum_(["minute", "second"]);

export declare namespace ShopifyIntegrationConfigsRateLimitPeriod {
    type Raw = "minute" | "second";
}
