/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const ShortEventDataParsedQueryOne: core.serialization.ObjectSchema<
    serializers.ShortEventDataParsedQueryOne.Raw,
    Hookdeck.ShortEventDataParsedQueryOne
> = core.serialization.object({});

export declare namespace ShortEventDataParsedQueryOne {
    interface Raw {}
}
