/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const ShortEventDataBodyOne: core.serialization.ObjectSchema<
    serializers.ShortEventDataBodyOne.Raw,
    Intercom.ShortEventDataBodyOne
> = core.serialization.object({});

export declare namespace ShortEventDataBodyOne {
    interface Raw {}
}
