/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const SourceVerificationOne: core.serialization.ObjectSchema<
    serializers.SourceVerificationOne.Raw,
    Hookdeck.SourceVerificationOne
> = core.serialization.object({});

export declare namespace SourceVerificationOne {
    interface Raw {}
}
