/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { TransformationExecutorOutputRequestParsedQueryOne } from "./TransformationExecutorOutputRequestParsedQueryOne";

export const TransformationExecutorOutputRequestParsedQuery: core.serialization.Schema<
    serializers.TransformationExecutorOutputRequestParsedQuery.Raw,
    Hookdeck.TransformationExecutorOutputRequestParsedQuery
> = core.serialization.undiscriminatedUnion([
    core.serialization.string().optional(),
    TransformationExecutorOutputRequestParsedQueryOne,
]);

export declare namespace TransformationExecutorOutputRequestParsedQuery {
    type Raw = (string | null | undefined) | TransformationExecutorOutputRequestParsedQueryOne.Raw;
}
