/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const TransformReference: core.serialization.ObjectSchema<
    serializers.TransformReference.Raw,
    Intercom.TransformReference
> = core.serialization.object({
    type: core.serialization.stringLiteral("transform"),
    transformationId: core.serialization.property("transformation_id", core.serialization.string()),
});

export declare namespace TransformReference {
    interface Raw {
        type: "transform";
        transformation_id: string;
    }
}
