/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { TransformationExecutorOutputRequestBodyOne } from "./TransformationExecutorOutputRequestBodyOne";

export const TransformationExecutorOutputRequestBody: core.serialization.Schema<
    serializers.TransformationExecutorOutputRequestBody.Raw,
    Hookdeck.TransformationExecutorOutputRequestBody
> = core.serialization.undiscriminatedUnion([
    core.serialization.string().optional(),
    TransformationExecutorOutputRequestBodyOne,
]);

export declare namespace TransformationExecutorOutputRequestBody {
    type Raw = (string | null | undefined) | TransformationExecutorOutputRequestBodyOne.Raw;
}
