/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { TransformReference } from "./TransformReference";
import { TransformFull } from "./TransformFull";

export const TransformRule: core.serialization.Schema<serializers.TransformRule.Raw, Hookdeck.TransformRule> =
    core.serialization.undiscriminatedUnion([TransformReference, TransformFull]);

export declare namespace TransformRule {
    type Raw = TransformReference.Raw | TransformFull.Raw;
}
