/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const TransformationExecutorOutputRequestParsedQueryOne: core.serialization.ObjectSchema<
    serializers.TransformationExecutorOutputRequestParsedQueryOne.Raw,
    Hookdeck.TransformationExecutorOutputRequestParsedQueryOne
> = core.serialization.object({});

export declare namespace TransformationExecutorOutputRequestParsedQueryOne {
    interface Raw {}
}
