/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { TransformRuleTransformation } from "./TransformRuleTransformation";

export const TransformRule: core.serialization.ObjectSchema<serializers.TransformRule.Raw, Hookdeck.TransformRule> =
    core.serialization.object({
        transformationId: core.serialization.property("transformation_id", core.serialization.string().optional()),
        transformation: TransformRuleTransformation.optional(),
    });

export declare namespace TransformRule {
    interface Raw {
        transformation_id?: string | null;
        transformation?: TransformRuleTransformation.Raw | null;
    }
}
