/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationWixType: core.serialization.Schema<
    serializers.VerificationWixType.Raw,
    Intercom.VerificationWixType
> = core.serialization.enum_(["wix", "WIX"]);

export declare namespace VerificationWixType {
    type Raw = "wix" | "WIX";
}
