/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationTwitterType: core.serialization.Schema<
    serializers.VerificationTwitterType.Raw,
    Hookdeck.VerificationTwitterType
> = core.serialization.enum_(["twitter"]);

export declare namespace VerificationTwitterType {
    type Raw = "twitter";
}
