/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const VerificationSquareType: core.serialization.Schema<
    serializers.VerificationSquareType.Raw,
    Hookdeck.VerificationSquareType
> = core.serialization.enum_(["square"]);

export declare namespace VerificationSquareType {
    type Raw = "square";
}
