/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationFavroConfigs } from "./VerificationFavroConfigs";

export const VerificationFavro: core.serialization.ObjectSchema<
    serializers.VerificationFavro.Raw,
    Hookdeck.VerificationFavro
> = core.serialization.object({
    configs: VerificationFavroConfigs.optional(),
});

export declare namespace VerificationFavro {
    interface Raw {
        configs?: VerificationFavroConfigs.Raw | null;
    }
}
