/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationPostmarkType: core.serialization.Schema<
    serializers.VerificationPostmarkType.Raw,
    Hookdeck.VerificationPostmarkType
> = core.serialization.enum_(["postmark"]);

export declare namespace VerificationPostmarkType {
    type Raw = "postmark";
}
