/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationOuraType: core.serialization.Schema<
    serializers.VerificationOuraType.Raw,
    Hookdeck.VerificationOuraType
> = core.serialization.enum_(["oura", "OURA"]);

export declare namespace VerificationOuraType {
    type Raw = "oura" | "OURA";
}
