/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";
import { VerificationBasicAuthType } from "./VerificationBasicAuthType";
import { VerificationBasicAuthConfigs } from "./VerificationBasicAuthConfigs";

export const VerificationBasicAuth: core.serialization.ObjectSchema<
    serializers.VerificationBasicAuth.Raw,
    Hookdeck.VerificationBasicAuth
> = core.serialization.object({
    type: VerificationBasicAuthType,
    configs: VerificationBasicAuthConfigs.optional(),
});

export declare namespace VerificationBasicAuth {
    interface Raw {
        type: VerificationBasicAuthType.Raw;
        configs?: VerificationBasicAuthConfigs.Raw | null;
    }
}
