/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { VerificationEnodeType } from "./VerificationEnodeType";
import { VerificationEnodeConfigs } from "./VerificationEnodeConfigs";

export const VerificationEnode: core.serialization.ObjectSchema<
    serializers.VerificationEnode.Raw,
    Intercom.VerificationEnode
> = core.serialization.object({
    type: VerificationEnodeType,
    configs: VerificationEnodeConfigs.optional(),
});

export declare namespace VerificationEnode {
    interface Raw {
        type: VerificationEnodeType.Raw;
        configs?: VerificationEnodeConfigs.Raw | null;
    }
}
