/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { VerificationHubspotType } from "./VerificationHubspotType";
import { VerificationHubspotConfigs } from "./VerificationHubspotConfigs";

export const VerificationHubspot: core.serialization.ObjectSchema<
    serializers.VerificationHubspot.Raw,
    Intercom.VerificationHubspot
> = core.serialization.object({
    type: VerificationHubspotType,
    configs: VerificationHubspotConfigs.optional(),
});

export declare namespace VerificationHubspot {
    interface Raw {
        type: VerificationHubspotType.Raw;
        configs?: VerificationHubspotConfigs.Raw | null;
    }
}
