/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationStripeType: core.serialization.Schema<
    serializers.VerificationStripeType.Raw,
    Hookdeck.VerificationStripeType
> = core.serialization.enum_(["stripe"]);

export declare namespace VerificationStripeType {
    type Raw = "stripe";
}
