/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { VerificationApiKeyType } from "./VerificationApiKeyType";
import { VerificationApiKeyConfigs } from "./VerificationApiKeyConfigs";

export const VerificationApiKey: core.serialization.ObjectSchema<
    serializers.VerificationApiKey.Raw,
    Intercom.VerificationApiKey
> = core.serialization.object({
    type: VerificationApiKeyType,
    configs: VerificationApiKeyConfigs.optional(),
});

export declare namespace VerificationApiKey {
    interface Raw {
        type: VerificationApiKeyType.Raw;
        configs?: VerificationApiKeyConfigs.Raw | null;
    }
}
