/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationFrontAppType: core.serialization.Schema<
    serializers.VerificationFrontAppType.Raw,
    Intercom.VerificationFrontAppType
> = core.serialization.enum_(["frontapp", "FRONTAPP"]);

export declare namespace VerificationFrontAppType {
    type Raw = "frontapp" | "FRONTAPP";
}
