/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationCommercelayerType: core.serialization.Schema<
    serializers.VerificationCommercelayerType.Raw,
    Hookdeck.VerificationCommercelayerType
> = core.serialization.enum_(["commercelayer", "COMMERCELAYER"]);

export declare namespace VerificationCommercelayerType {
    type Raw = "commercelayer" | "COMMERCELAYER";
}
