/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationShopifyType: core.serialization.Schema<
    serializers.VerificationShopifyType.Raw,
    Intercom.VerificationShopifyType
> = core.serialization.enum_(["shopify", "SHOPIFY"]);

export declare namespace VerificationShopifyType {
    type Raw = "shopify" | "SHOPIFY";
}
