/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationAwssnsType: core.serialization.Schema<
    serializers.VerificationAwssnsType.Raw,
    Intercom.VerificationAwssnsType
> = core.serialization.enum_(["aws_sns", "AWS_SNS"]);

export declare namespace VerificationAwssnsType {
    type Raw = "aws_sns" | "AWS_SNS";
}
