/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationRechargeConfigsEncoding: core.serialization.Schema<
    serializers.VerificationRechargeConfigsEncoding.Raw,
    Intercom.VerificationRechargeConfigsEncoding
> = core.serialization.enum_(["base64", "base64url", "hex"]);

export declare namespace VerificationRechargeConfigsEncoding {
    type Raw = "base64" | "base64url" | "hex";
}
