/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationXeroType: core.serialization.Schema<
    serializers.VerificationXeroType.Raw,
    Intercom.VerificationXeroType
> = core.serialization.enum_(["xero", "XERO"]);

export declare namespace VerificationXeroType {
    type Raw = "xero" | "XERO";
}
