/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationStripeType: core.serialization.Schema<
    serializers.VerificationStripeType.Raw,
    Intercom.VerificationStripeType
> = core.serialization.enum_(["stripe", "STRIPE"]);

export declare namespace VerificationStripeType {
    type Raw = "stripe" | "STRIPE";
}
