/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationAdyenType: core.serialization.Schema<
    serializers.VerificationAdyenType.Raw,
    Intercom.VerificationAdyenType
> = core.serialization.enum_(["adyen", "ADYEN"]);

export declare namespace VerificationAdyenType {
    type Raw = "adyen" | "ADYEN";
}
