/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const VerificationTokenIoType: core.serialization.Schema<
    serializers.VerificationTokenIoType.Raw,
    Hookdeck.VerificationTokenIoType
> = core.serialization.enum_(["tokenio"]);

export declare namespace VerificationTokenIoType {
    type Raw = "tokenio";
}
