/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationHmacType: core.serialization.Schema<
    serializers.VerificationHmacType.Raw,
    Intercom.VerificationHmacType
> = core.serialization.enum_(["hmac", "HMAC"]);

export declare namespace VerificationHmacType {
    type Raw = "hmac" | "HMAC";
}
