/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationCourierType: core.serialization.Schema<
    serializers.VerificationCourierType.Raw,
    Hookdeck.VerificationCourierType
> = core.serialization.enum_(["courier"]);

export declare namespace VerificationCourierType {
    type Raw = "courier";
}
