/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationCourierType: core.serialization.Schema<
    serializers.VerificationCourierType.Raw,
    Intercom.VerificationCourierType
> = core.serialization.enum_(["courier", "COURIER"]);

export declare namespace VerificationCourierType {
    type Raw = "courier" | "COURIER";
}
