/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationTwitchType: core.serialization.Schema<
    serializers.VerificationTwitchType.Raw,
    Hookdeck.VerificationTwitchType
> = core.serialization.enum_(["twitch"]);

export declare namespace VerificationTwitchType {
    type Raw = "twitch";
}
