/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationSvixType: core.serialization.Schema<
    serializers.VerificationSvixType.Raw,
    Hookdeck.VerificationSvixType
> = core.serialization.enum_(["svix", "SVIX"]);

export declare namespace VerificationSvixType {
    type Raw = "svix" | "SVIX";
}
