/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationApiKeyType: core.serialization.Schema<
    serializers.VerificationApiKeyType.Raw,
    Intercom.VerificationApiKeyType
> = core.serialization.enum_(["api_key", "API_KEY"]);

export declare namespace VerificationApiKeyType {
    type Raw = "api_key" | "API_KEY";
}
