/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationTrelloType: core.serialization.Schema<
    serializers.VerificationTrelloType.Raw,
    Intercom.VerificationTrelloType
> = core.serialization.enum_(["trello", "TRELLO"]);

export declare namespace VerificationTrelloType {
    type Raw = "trello" | "TRELLO";
}
