/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationSyncteraType: core.serialization.Schema<
    serializers.VerificationSyncteraType.Raw,
    Hookdeck.VerificationSyncteraType
> = core.serialization.enum_(["synctera"]);

export declare namespace VerificationSyncteraType {
    type Raw = "synctera";
}
