/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const VerificationFavroType: core.serialization.Schema<
    serializers.VerificationFavroType.Raw,
    Hookdeck.VerificationFavroType
> = core.serialization.enum_(["favro"]);

export declare namespace VerificationFavroType {
    type Raw = "favro";
}
