/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const VerificationCommercelayerType: core.serialization.Schema<
    serializers.VerificationCommercelayerType.Raw,
    Hookdeck.VerificationCommercelayerType
> = core.serialization.enum_(["commercelayer"]);

export declare namespace VerificationCommercelayerType {
    type Raw = "commercelayer";
}
