/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationNmiPaymentGatewayConfigs } from "./VerificationNmiPaymentGatewayConfigs";

export const VerificationNmiPaymentGateway: core.serialization.ObjectSchema<
    serializers.VerificationNmiPaymentGateway.Raw,
    Hookdeck.VerificationNmiPaymentGateway
> = core.serialization.object({
    configs: VerificationNmiPaymentGatewayConfigs.optional(),
});

export declare namespace VerificationNmiPaymentGateway {
    interface Raw {
        configs?: VerificationNmiPaymentGatewayConfigs.Raw | null;
    }
}
