/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationWorkOsConfigs } from "./VerificationWorkOsConfigs";

export const VerificationWorkOs: core.serialization.ObjectSchema<
    serializers.VerificationWorkOs.Raw,
    Hookdeck.VerificationWorkOs
> = core.serialization.object({
    configs: VerificationWorkOsConfigs.optional(),
});

export declare namespace VerificationWorkOs {
    interface Raw {
        configs?: VerificationWorkOsConfigs.Raw | null;
    }
}
