/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationRazorpayConfigs } from "./VerificationRazorpayConfigs";

export const VerificationRazorpay: core.serialization.ObjectSchema<
    serializers.VerificationRazorpay.Raw,
    Hookdeck.VerificationRazorpay
> = core.serialization.object({
    configs: VerificationRazorpayConfigs.optional(),
});

export declare namespace VerificationRazorpay {
    interface Raw {
        configs?: VerificationRazorpayConfigs.Raw | null;
    }
}
