/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationAwssnsConfigs: core.serialization.ObjectSchema<
    serializers.VerificationAwssnsConfigs.Raw,
    Intercom.VerificationAwssnsConfigs
> = core.serialization.object({});

export declare namespace VerificationAwssnsConfigs {
    interface Raw {}
}
