/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationWixConfigs } from "./VerificationWixConfigs";

export const VerificationWix: core.serialization.ObjectSchema<
    serializers.VerificationWix.Raw,
    Hookdeck.VerificationWix
> = core.serialization.object({
    configs: VerificationWixConfigs.optional(),
});

export declare namespace VerificationWix {
    interface Raw {
        configs?: VerificationWixConfigs.Raw | null;
    }
}
