/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationLinearType: core.serialization.Schema<
    serializers.VerificationLinearType.Raw,
    Hookdeck.VerificationLinearType
> = core.serialization.enum_(["linear", "LINEAR"]);

export declare namespace VerificationLinearType {
    type Raw = "linear" | "LINEAR";
}
