/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationTokenIoType: core.serialization.Schema<
    serializers.VerificationTokenIoType.Raw,
    Intercom.VerificationTokenIoType
> = core.serialization.enum_(["tokenio", "TOKENIO"]);

export declare namespace VerificationTokenIoType {
    type Raw = "tokenio" | "TOKENIO";
}
