/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationApiKeyConfigs: core.serialization.ObjectSchema<
    serializers.VerificationApiKeyConfigs.Raw,
    Intercom.VerificationApiKeyConfigs
> = core.serialization.object({
    headerKey: core.serialization.property("header_key", core.serialization.string()),
    apiKey: core.serialization.property("api_key", core.serialization.string()),
});

export declare namespace VerificationApiKeyConfigs {
    interface Raw {
        header_key: string;
        api_key: string;
    }
}
