/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationPipedriveType: core.serialization.Schema<
    serializers.VerificationPipedriveType.Raw,
    Hookdeck.VerificationPipedriveType
> = core.serialization.enum_(["pipedrive", "PIPEDRIVE"]);

export declare namespace VerificationPipedriveType {
    type Raw = "pipedrive" | "PIPEDRIVE";
}
