/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationSyncteraConfigs } from "./VerificationSyncteraConfigs";

export const VerificationSynctera: core.serialization.ObjectSchema<
    serializers.VerificationSynctera.Raw,
    Hookdeck.VerificationSynctera
> = core.serialization.object({
    configs: VerificationSyncteraConfigs.optional(),
});

export declare namespace VerificationSynctera {
    interface Raw {
        configs?: VerificationSyncteraConfigs.Raw | null;
    }
}
