/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { VerificationMailgunType } from "./VerificationMailgunType";
import { VerificationMailgunConfigs } from "./VerificationMailgunConfigs";

export const VerificationMailgun: core.serialization.ObjectSchema<
    serializers.VerificationMailgun.Raw,
    Intercom.VerificationMailgun
> = core.serialization.object({
    type: VerificationMailgunType,
    configs: VerificationMailgunConfigs.optional(),
});

export declare namespace VerificationMailgun {
    interface Raw {
        type: VerificationMailgunType.Raw;
        configs?: VerificationMailgunConfigs.Raw | null;
    }
}
