/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationGitLabConfigs } from "./VerificationGitLabConfigs";

export const VerificationGitLab: core.serialization.ObjectSchema<
    serializers.VerificationGitLab.Raw,
    Hookdeck.VerificationGitLab
> = core.serialization.object({
    configs: VerificationGitLabConfigs.optional(),
});

export declare namespace VerificationGitLab {
    interface Raw {
        configs?: VerificationGitLabConfigs.Raw | null;
    }
}
