/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationCloudSignalConfigs: core.serialization.ObjectSchema<
    serializers.VerificationCloudSignalConfigs.Raw,
    Intercom.VerificationCloudSignalConfigs
> = core.serialization.object({
    apiKey: core.serialization.property("api_key", core.serialization.string()),
});

export declare namespace VerificationCloudSignalConfigs {
    interface Raw {
        api_key: string;
    }
}
