/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { VerificationPersonaType } from "./VerificationPersonaType";
import { VerificationPersonaConfigs } from "./VerificationPersonaConfigs";

export const VerificationPersona: core.serialization.ObjectSchema<
    serializers.VerificationPersona.Raw,
    Intercom.VerificationPersona
> = core.serialization.object({
    type: VerificationPersonaType,
    configs: VerificationPersonaConfigs.optional(),
});

export declare namespace VerificationPersona {
    interface Raw {
        type: VerificationPersonaType.Raw;
        configs?: VerificationPersonaConfigs.Raw | null;
    }
}
