/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Hookdeck from "../../api";
import * as core from "../../core";

export const VerificationShopifyType: core.serialization.Schema<
    serializers.VerificationShopifyType.Raw,
    Hookdeck.VerificationShopifyType
> = core.serialization.enum_(["shopify"]);

export declare namespace VerificationShopifyType {
    type Raw = "shopify";
}
