/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";
import { VerificationTebexConfigs } from "./VerificationTebexConfigs";

export const VerificationTebex: core.serialization.ObjectSchema<
    serializers.VerificationTebex.Raw,
    Hookdeck.VerificationTebex
> = core.serialization.object({
    configs: VerificationTebexConfigs.optional(),
});

export declare namespace VerificationTebex {
    interface Raw {
        configs?: VerificationTebexConfigs.Raw | null;
    }
}
