/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Hookdeck from "../../api/index";
import * as core from "../../core";

export const VerificationWorkOsType: core.serialization.Schema<
    serializers.VerificationWorkOsType.Raw,
    Hookdeck.VerificationWorkOsType
> = core.serialization.enum_(["workos"]);

export declare namespace VerificationWorkOsType {
    type Raw = "workos";
}
