/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";

export const VerificationHubspotType: core.serialization.Schema<
    serializers.VerificationHubspotType.Raw,
    Intercom.VerificationHubspotType
> = core.serialization.enum_(["hubspot", "HUBSPOT"]);

export declare namespace VerificationHubspotType {
    type Raw = "hubspot" | "HUBSPOT";
}
