/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Intercom from "../../api";
import * as core from "../../core";
import { VerificationStripeType } from "./VerificationStripeType";
import { VerificationStripeConfigs } from "./VerificationStripeConfigs";

export const VerificationStripe: core.serialization.ObjectSchema<
    serializers.VerificationStripe.Raw,
    Intercom.VerificationStripe
> = core.serialization.object({
    type: VerificationStripeType,
    configs: VerificationStripeConfigs.optional(),
});

export declare namespace VerificationStripe {
    interface Raw {
        type: VerificationStripeType.Raw;
        configs?: VerificationStripeConfigs.Raw | null;
    }
}
