/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";

export const BookmarkListRequestDir: core.serialization.Schema<
    serializers.BookmarkListRequestDir.Raw,
    Hookdeck.BookmarkListRequestDir
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace BookmarkListRequestDir {
    type Raw = "asc" | "desc";
}
