/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";

export const IssueUpdateRequestStatus: core.serialization.Schema<
    serializers.IssueUpdateRequestStatus.Raw,
    Hookdeck.IssueUpdateRequestStatus
> = core.serialization.enum_(["OPENED", "IGNORED", "ACKNOWLEDGED", "RESOLVED"]);

export declare namespace IssueUpdateRequestStatus {
    type Raw = "OPENED" | "IGNORED" | "ACKNOWLEDGED" | "RESOLVED";
}
