/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const IssueCountRequestType: core.serialization.Schema<
    serializers.IssueCountRequestType.Raw,
    Intercom.IssueCountRequestType
> = core.serialization.enum_(["delivery", "transformation", "backpressure"]);

export declare namespace IssueCountRequestType {
    type Raw = "delivery" | "transformation" | "backpressure";
}
