/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";

export const IssueListRequestType: core.serialization.Schema<
    serializers.IssueListRequestType.Raw,
    Hookdeck.IssueListRequestType
> = core.serialization.enum_(["delivery", "transformation", "backpressure"]);

export declare namespace IssueListRequestType {
    type Raw = "delivery" | "transformation" | "backpressure";
}
