/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const IssueCountRequestStatus: core.serialization.Schema<
    serializers.IssueCountRequestStatus.Raw,
    Hookdeck.IssueCountRequestStatus
> = core.serialization.enum_(["OPENED", "IGNORED", "ACKNOWLEDGED", "RESOLVED"]);

export declare namespace IssueCountRequestStatus {
    type Raw = "OPENED" | "IGNORED" | "ACKNOWLEDGED" | "RESOLVED";
}
