/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransformationListExecutionRequestLogLevel = "debug" | "info" | "warn" | "error" | "fatal";

export const TransformationListExecutionRequestLogLevel = {
    Debug: "debug",
    Info: "info",
    Warn: "warn",
    Error: "error",
    Fatal: "fatal",
} as const;
