/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Period to rate limit attempts
 */
export type DestinationUpsertRequestRateLimitPeriod = "second" | "minute" | "hour" | "concurrent";

export const DestinationUpsertRequestRateLimitPeriod = {
    Second: "second",
    Minute: "minute",
    Hour: "hour",
    Concurrent: "concurrent",
} as const;
