/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DestinationListRequestDir = "asc" | "desc";

export const DestinationListRequestDir = {
    Asc: "asc",
    Desc: "desc",
} as const;
