/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../..";

/**
 * @example
 *     {}
 */
export interface RequestListRequest {
    id?: string;
    status?: Intercom.RequestListRequestStatus;
    rejectionCause?: Intercom.RequestRejectionCause;
    sourceId?: string;
    verified?: boolean;
    searchTerm?: string;
    headers?: string;
    body?: string;
    parsedQuery?: string;
    path?: string;
    ignoredCount?: number;
    eventsCount?: number;
    ingestedAt?: Date;
    bulkRetryId?: string;
    include?: "data";
    orderBy?: Intercom.RequestListRequestOrderBy;
    dir?: Intercom.RequestListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
