/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../..";

/**
 * @example
 *     {}
 */
export interface RequestListRequest {
    id?: string;
    status?: Hookdeck.RequestListRequestStatus;
    rejectionCause?: Hookdeck.RequestRejectionCause;
    sourceId?: string;
    verified?: boolean;
    searchTerm?: string;
    headers?: string;
    body?: string;
    parsedQuery?: string;
    path?: string;
    ignoredCount?: number;
    eventsCount?: number;
    ingestedAt?: Date;
    bulkRetryId?: string;
    include?: "data";
    orderBy?: Hookdeck.RequestListRequestOrderBy;
    dir?: Hookdeck.RequestListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
