/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ConnectionListRequest {
    id?: string | string[];
    name?: string;
    destinationId?: string | string[];
    sourceId?: string | string[];
    disabled?: boolean;
    disabledAt?: Date;
    fullName?: string;
    pausedAt?: Date;
    orderBy?: Hookdeck.ConnectionListRequestOrderBy;
    dir?: Hookdeck.ConnectionListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
