/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EventBulkRetryCreateRequestQuerySuccessfulAtAny {
    gt?: Date;
    gte?: Date;
    le?: Date;
    lte?: Date;
    any?: boolean;
}
