/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../index";

/**
 * Filter by `created_at` date using a date operator
 */
export type EventBulkRetryCreateRequestQueryCreatedAt = Date | Hookdeck.Operators;
