/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Filter by event IDs
 */
export type EventBulkRetryCreateRequestQueryId =
    /**
     * Event ID */
    string | string[];
