/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../index";

/**
 * Filter by error code code
 */
export type EventBulkRetryCreateRequestQueryErrorCode = Hookdeck.AttemptErrorCodes | Hookdeck.AttemptErrorCodes[];
