/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../..";

/**
 * Filter by `last_attempt_at` date using a date operator
 */
export type EventBulkRetryCreateRequestQueryLastAttemptAt =
    | Date
    | Hookdeck.EventBulkRetryCreateRequestQueryLastAttemptAtAny;
