/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../..";

/**
 * Filter properties for the events to be included in the bulk retry
 */
export interface EventBulkRetryCreateRequestQuery {
    /** Filter by event IDs */
    id?: Intercom.EventBulkRetryCreateRequestQueryId;
    /** Lifecyle status of the event */
    status?: Intercom.EventBulkRetryCreateRequestQueryStatus;
    /** Filter by webhook connection IDs */
    webhookId?: Intercom.EventBulkRetryCreateRequestQueryWebhookId;
    /** Filter by destination IDs */
    destinationId?: Intercom.EventBulkRetryCreateRequestQueryDestinationId;
    /** Filter by source IDs */
    sourceId?: Intercom.EventBulkRetryCreateRequestQuerySourceId;
    /** Filter by number of attempts */
    attempts?: Intercom.EventBulkRetryCreateRequestQueryAttempts;
    /** Filter by HTTP response status code */
    responseStatus?: Intercom.EventBulkRetryCreateRequestQueryResponseStatus;
    /** Filter by `successful_at` date using a date operator */
    successfulAt?: Intercom.EventBulkRetryCreateRequestQuerySuccessfulAt;
    /** Filter by `created_at` date using a date operator */
    createdAt?: Intercom.EventBulkRetryCreateRequestQueryCreatedAt;
    /** Filter by error code code */
    errorCode?: Intercom.EventBulkRetryCreateRequestQueryErrorCode;
    /** Filter by CLI IDs. `?[any]=true` operator for any CLI. */
    cliId?: Intercom.EventBulkRetryCreateRequestQueryCliId;
    /** Filter by `last_attempt_at` date using a date operator */
    lastAttemptAt?: Intercom.EventBulkRetryCreateRequestQueryLastAttemptAt;
    /** URL Encoded string of the value to match partially to the body, headers, parsed_query or path */
    searchTerm?: string;
    /** URL Encoded string of the JSON to match to the data headers */
    headers?: Intercom.EventBulkRetryCreateRequestQueryHeaders;
    /** URL Encoded string of the JSON to match to the data body */
    body?: Intercom.EventBulkRetryCreateRequestQueryBody;
    /** URL Encoded string of the JSON to match to the parsed query (JSON representation of the query) */
    parsedQuery?: Intercom.EventBulkRetryCreateRequestQueryParsedQuery;
    /** URL Encoded string of the value to match partially to the path */
    path?: string;
    cliUserId?: Intercom.EventBulkRetryCreateRequestQueryCliUserId;
    issueId?: Intercom.EventBulkRetryCreateRequestQueryIssueId;
    eventDataId?: Intercom.EventBulkRetryCreateRequestQueryEventDataId;
    bulkRetryId?: Intercom.EventBulkRetryCreateRequestQueryBulkRetryId;
}
