/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EventBulkRetryListRequestDir = "asc" | "desc";

export const EventBulkRetryListRequestDir = {
    Asc: "asc",
    Desc: "desc",
} as const;
