/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../index";

/**
 * Filter by number of attempts
 */
export type EventBulkRetryCreateRequestQueryAttempts = number | Hookdeck.Operators;
