/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../..";

/**
 * @example
 *     {}
 */
export interface IgnoredEventBulkRetryListRequest {
    cancelledAt?: Date;
    completedAt?: Date;
    createdAt?: Date;
    id?: string;
    queryPartialMatch?: boolean;
    inProgress?: boolean;
    orderBy?: Intercom.IgnoredEventBulkRetryListRequestOrderBy;
    dir?: Intercom.IgnoredEventBulkRetryListRequestDir;
    limit?: number;
    next?: string;
    prev?: string;
}
