/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../..";

/**
 * @example
 *     {}
 */
export interface NotificationUpdateRequest {
    /** Enable or disable webhook notifications on the workspace */
    enabled?: boolean;
    /** List of topics to send notifications for */
    topics?: Hookdeck.TopicsValue[];
    /** The Hookdeck Source to send the webhook to */
    sourceId?: string;
}
