/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";
import { TransformationRunRequestRequestBodyZero } from "./TransformationRunRequestRequestBodyZero";

export const TransformationRunRequestRequestBody: core.serialization.Schema<
    serializers.TransformationRunRequestRequestBody.Raw,
    Hookdeck.TransformationRunRequestRequestBody
> = core.serialization.undiscriminatedUnion([TransformationRunRequestRequestBodyZero, core.serialization.string()]);

export declare namespace TransformationRunRequestRequestBody {
    type Raw = TransformationRunRequestRequestBodyZero.Raw | string;
}
