/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Hookdeck from "../../../../api/index";
import * as core from "../../../../core";

export const TransformationRunRequestRequestBodyZero: core.serialization.ObjectSchema<
    serializers.TransformationRunRequestRequestBodyZero.Raw,
    Hookdeck.TransformationRunRequestRequestBodyZero
> = core.serialization.object({});

export declare namespace TransformationRunRequestRequestBodyZero {
    interface Raw {}
}
