/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const TransformationRunRequestRequestBodyZero: core.serialization.ObjectSchema<
    serializers.TransformationRunRequestRequestBodyZero.Raw,
    Intercom.TransformationRunRequestRequestBodyZero
> = core.serialization.object({});

export declare namespace TransformationRunRequestRequestBodyZero {
    interface Raw {}
}
