/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Hookdeck from "../../../../api";
import * as core from "../../../../core";

export const TransformationListExecutionRequestOrderBy: core.serialization.Schema<
    serializers.TransformationListExecutionRequestOrderBy.Raw,
    Hookdeck.TransformationListExecutionRequestOrderBy
> = core.serialization.enum_(["created_at"]);

export declare namespace TransformationListExecutionRequestOrderBy {
    type Raw = "created_at";
}
