/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Intercom from "../../../../api";
import * as core from "../../../../core";

export const TransformationListExecutionRequestLogLevel: core.serialization.Schema<
    serializers.TransformationListExecutionRequestLogLevel.Raw,
    Intercom.TransformationListExecutionRequestLogLevel
> = core.serialization.enum_(["debug", "info", "warn", "error", "fatal"]);

export declare namespace TransformationListExecutionRequestLogLevel {
    type Raw = "debug" | "info" | "warn" | "error" | "fatal";
}
