/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const HookdeckEnvironment = {
    Default: "https://api.hookdeck.com/2024-03-01",
} as const;

export type HookdeckEnvironment = typeof HookdeckEnvironment.Default;
