/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Hookdeck from "../../../../../api/index";
import * as core from "../../../../../core";
import { Rule } from "../../../../types/Rule";

export const ConnectionUpdateRequest: core.serialization.Schema<
    serializers.ConnectionUpdateRequest.Raw,
    Hookdeck.ConnectionUpdateRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    rules: core.serialization.list(Rule).optional(),
});

export declare namespace ConnectionUpdateRequest {
    interface Raw {
        name?: string | null;
        description?: string | null;
        rules?: Rule.Raw[] | null;
    }
}
