/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Intercom from "../../../../../api";
import * as core from "../../../../../core";
import { EventBulkRetryCreateRequestQuery } from "../../types/EventBulkRetryCreateRequestQuery";

export const EventBulkRetryCreateRequest: core.serialization.Schema<
    serializers.EventBulkRetryCreateRequest.Raw,
    Intercom.EventBulkRetryCreateRequest
> = core.serialization.object({
    query: EventBulkRetryCreateRequestQuery.optional(),
});

export declare namespace EventBulkRetryCreateRequest {
    interface Raw {
        query?: EventBulkRetryCreateRequestQuery.Raw | null;
    }
}
