/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Hookdeck from "../../../index";

/**
 * Filter by count of events
 */
export type RequestBulkRetryCreateRequestQueryEventsCount = number | Hookdeck.Operators | number[];
