/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../..";

/**
 * Filter by rejection cause
 */
export type RequestBulkRetryCreateRequestQueryRejectionCause =
    | Intercom.RequestRejectionCause
    | Intercom.RequestRejectionCause[];
